server:
  port: 8084

spring:
  application:
    name: projectbrad
  datasource:
    url: jdbc:postgresql://${PROJECTBRAD_DATABASE_URL:localhost}:5432/projeto-db
    username: ${PROJECTBRAD_DATABASE_USERNAME:postgres}
    password: ${PROJECTBRAD_DATABASE_PASSWORD:}
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${PROJECTBRAD_DATABASE_MAX_POOL:20}
      connection-timeout: 20000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
      
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    contexts: ${spring.profiles.active}